In [ ]:
#### import numpy as np

# -----------------------------------------
# 1. Take Matrix Input from User
# -----------------------------------------
def input_matrix():
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))
    print("Enter matrix values row by row (space separated):")

    matrix = []
    for _ in range(rows):
        row = list(map(float, input().split()))
        matrix.append(row)

    return np.array(matrix)

# -----------------------------------------
# 2. Basic Matrix Operations
# -----------------------------------------

def matrix_addition():
    print("Enter Matrix A:")
    A = input_matrix()
    print("Enter Matrix B:")
    B = input_matrix()
    print("A + B =\n", A + B)

def matrix_subtraction():
    print("Enter Matrix A:")
    A = input_matrix()
    print("Enter Matrix B:")
    B = input_matrix()
    print("A - B =\n", A - B)

def matrix_multiplication():
    print("Enter Matrix A:")
    A = input_matrix()
    print("Enter Matrix B:")
    B = input_matrix()
    print("A × B =\n", A @ B)

def scalar_multiplication():
    print("Enter Matrix A:")
    A = input_matrix()
    k = float(input("Enter scalar value: "))
    print("k × A =\n", k * A)

# -----------------------------------------
# 3. Advanced Operations
# -----------------------------------------

def matrix_transpose():
    print("Enter Matrix:")
    A = input_matrix()
    print("Transpose =\n", A.T)

def matrix_determinant():
    print("Enter Square Matrix:")
    A = input_matrix()
    print("Determinant =", np.linalg.det(A))

def matrix_rank():
    print("Enter Matrix:")
    A = input_matrix()
    print("Rank =", np.linalg.matrix_rank(A))

def matrix_inverse():
    print("Enter Square Matrix:")
    A = input_matrix()
    try:
        print("Inverse =\n", np.linalg.inv(A))
    except:
        print("Matrix is singular — inverse does NOT exist.")

def eigen_values_vectors():
    print("Enter Square Matrix:")
    A = input_matrix()
    values, vectors = np.linalg.eig(A)
    print("Eigenvalues:\n", values)
    print("Eigenvectors:\n", vectors)

# -----------------------------------------
# 4. Solve System of Linear Equations
# -----------------------------------------
def solve_linear_equations():
    print("Enter Coefficient Matrix A:")
    A = input_matrix()
    print("Enter Constant Matrix b (column vector):")
    b = input_matrix()
    
    try:
        x = np.linalg.solve(A, b)
        print("Solution x =\n", x)
    except:
        print("No unique solution exists for Ax = b")

# -----------------------------------------
# 5. MAIN MENU
# -----------------------------------------
def main():
    while True:
        print("\nMatrix Algebra System (MAS)")
        print("----------------------------")
        print("1. Matrix Addition")
        print("2. Matrix Subtraction")
        print("3. Matrix Multiplication")
        print("4. Scalar Multiplication")
        print("5. Transpose")
        print("6. Determinant")
        print("7. Inverse")
        print("8. Rank")
        print("9. Eigenvalues & Eigenvectors")
        print("10. Solve System of Equations (Ax = b)")
        print("11. Exit")

        choice = int(input("Choose an option: "))

        if choice == 1: matrix_addition()
        elif choice == 2: matrix_subtraction()
        elif choice == 3: matrix_multiplication()
        elif choice == 4: scalar_multiplication()
        elif choice == 5: matrix_transpose()
        elif choice == 6: matrix_determinant()
        elif choice == 7: matrix_inverse()
        elif choice == 8: matrix_rank()
        elif choice == 9: eigen_values_vectors()
        elif choice == 10: solve_linear_equations()
        elif choice == 11:
            print("Exiting...")
            break
        else:
            print("Invalid choice. Try again.")

main()



Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  1


Enter Matrix A:


Enter number of rows:  2
Enter number of columns:  3


Enter matrix values row by row (space separated):


 1 2 3
 2 3 4


Enter Matrix B:


Enter number of rows:  2
Enter number of columns:  3


Enter matrix values row by row (space separated):


 2 3 4
 4 5 6


A + B =
 [[ 3.  5.  7.]
 [ 6.  8. 10.]]

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  4


Enter Matrix A:


Enter number of rows:  2
Enter number of columns:  3


Enter matrix values row by row (space separated):


 2 3 4
 3 4 3
Enter scalar value:  7


k × A =
 [[14. 21. 28.]
 [21. 28. 21.]]

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  6


Enter Square Matrix:


Enter number of rows:  2 
Enter number of columns:  2


Enter matrix values row by row (space separated):


 1 2
 3 4


Determinant = -2.0000000000000004

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  5


Enter Matrix:


Enter number of rows:  3
Enter number of columns:  5


Enter matrix values row by row (space separated):


 1 2 3 4 5
 3 4 5 6 7
 4 5 6 7 8


Transpose =
 [[1. 3. 4.]
 [2. 4. 5.]
 [3. 5. 6.]
 [4. 6. 7.]
 [5. 7. 8.]]

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  9


Enter Square Matrix:


Enter number of rows:  3
Enter number of columns:  3


Enter matrix values row by row (space separated):


 1 2 3
 8 9 10
 11 12 13


Eigenvalues:
 [ 2.42377392e+01 -1.23773920e+00  3.24024923e-16]
Eigenvectors:
 [[ 0.15304805  0.83365521  0.40824829]
 [ 0.59711062 -0.12626418 -0.81649658]
 [ 0.78742314 -0.5376582   0.40824829]]

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit


Choose an option:  10


Enter Coefficient Matrix A:


Enter number of rows:  2
Enter number of columns:  2


Enter matrix values row by row (space separated):


 1 3 
 1 2


Enter Constant Matrix b (column vector):


Enter number of rows:  2
Enter number of columns:  2


Enter matrix values row by row (space separated):


 1 0 
 0 1


Solution x =
 [[-2.  3.]
 [ 1. -1.]]

Matrix Algebra System (MAS)
----------------------------
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Rank
9. Eigenvalues & Eigenvectors
10. Solve System of Equations (Ax = b)
11. Exit
